### PR TITLE
Migrate CityCoins Protocol to xDAO structure

### LINKED ISSUE #14: Reduce duplicate functions
The `or-default` getters should be the default. This may affect some internal functions and needs a thorough review.

We should also look at the cost difference between returning a single variable or a tuple with grouped information, especially for the purely user facing getters. 

This would reduce the number of needed queries, ports over well [to the API](https://github.com/citycoins/api), and could be something we define the TS types for like we have in some of the other repos.

Publishing those would make it a lot easier for developers to know what data to expect without having to query each individual thing.

### LINKED ISSUE #15: Read only functions should return some/none
There are a few different return types for read-only functions in the CityCoins contracts, and we may not need to throw errors here but instead return `none`.

This should help with the logic used in client-side apps, and makes it so that read-only functions always return a value rather than the ok/err response.

### LINKED ISSUE #17: Remove memo from mining transactions
The `mine-tokens` function allows for an optional memo `(buff 34)`.

The `mine-many` function only accepts a list of `uint` values.

We should evaluate the usage of the memo in the mining transactions and if that is still a necessary feature.

### LINKED ISSUE #20: Add prettier config
Consistency is key!

### LINKED ISSUE #23: City Registry Structure
While implementing the city registry, it's purpose is starting to evolve.

Initially, it was created to take a city name as a string, and store/convert that into an ID used elsewhere.

Now a few more things have been added, and the basic structure is listed at the end of the issue.

Opening this to review as the work progresses and see if there is a better/cleaner approach.

The goal as of right now is to have:
- each city name associated with an ID (same as user principals)
- each city can have a number of named treasuries
- each city contains its activation information
- each city can have a number of supported tokens
- each city's coinbase should be sourced from the extension

---

City Registry

- var: city nonce
- map: city name, city id
- map: city id, city name

City Treasury

- map: city id, treasury nonce
- map: city id + treasury id, treasury name
- map: city id + treasury name, treasury id
- map: city id + treasury id, principal

City Activation

- map: city id, status
- map: city id, activation details

City Tokens

- map: city id, token nonce
- map: city id + token id, principal
- map: city id + token address, id
- map: city id, token id + token address

City Coinbase

- map: city id, thresholds
- map: city id, amounts

### LINKED ISSUE #26: Restructure contracts layout
Based on feedback from @radicleart and considering the default template for contracts, it would be easier to separate everything consistently, e.g.

1. imports / traits
2. token definitions
3. data var definitions
4. constants
5. data map definitions
6. public functions
7. read only functions 
8. private functions

The old style of grouping items together (e.g. map + getter + setter) came from the original size of the CityCoins core contract. Now that things are split up, taking this approach should make things more readable.

### LINKED ISSUE #27: Update test names and locations
After looking through what we have on `feat/migration` and `feat/migrationplustests`, it looks like having the test proposals grouped under the `contracts` directory will get cluttered very fast.

One idea is to change up the structure so the tests are stored somewhere else, e.g.

```
contracts <-- only protocol code, no tests
  extensions <-- (ccdNNN)
  external <-- (ccext-)
  proposals <-- (ccip-)
  traits <-- (leave as-is)
tests
  contracts <-- (test proposals)
    test-ccd001-direct-execute-NNN.clar
    test-ccd002-treasury-NNN.clar
    test-ccip012-bootstrap.clar
  extensions <-- (leave as-is)
    ccd001-direct-execute.test.ts
```

That should scale better, be easier to read, and from there we can start to identify any relevant patterns in the test proposals themselves.

Right now just looking at `ccip-test-treasury-006.clar` or the newer `test-ccd002-treasury-006.clar` doesn't tell me much about the test, but we should stick with it for now and look at it alongside #3 for a future refactor.

With fuzzing we could do cool things like setting up the model for what a city looks like it then running the tests on a bunch of different inputs!

### LINKED ISSUE #28: Add more descriptive error codes
Right now a lot of the contract is scoped out with `ERR_INVALID_PARAMS` as a placeholder - we need to expand the errors to be more descriptive after the first round of code changes are complete.

### LINKED ISSUE #29: Update error code numbering
Alongside #28 it'd be nice to implement a more consistent error numbering scheme. 

Right now it's setup so that:

```
basedao - 1000
ccd001  - 3000
ccd002  - 3100
ccdd03  - 3200
... and so on
```

This doesn't make it easy to tell which errors go with each contract.

Instead, we should do something that aligns with the extension names themselves, e.g.

```
basedao -    900
ccd001  -   1000
ccd002  -   2000
ccd009  -   9000
ccd133  - 133000
```

We've got plenty of room with `uint`s!

### LINKED ISSUE #31: Simplify testing for ccd005-city-data
There are some patterns in the code that it looks like we could simplify by adding constant declarations at the top, e.g.

```ts
const miaCityId = 1
const miaMiningTreasury = 1
const miaMiningTreasury = 2

const nycCityId = 2
const nycMiningTreasury = 1
const nycMiningTreasury = 2
```

This would be good to revisit on a second pass once the tests are complete.

It'd likely be a good step toward #3 as well.

### LINKED ISSUE #33: Cost testing between original protocol and DAO version
This issue will be the main placeholder for cost testing information, similar to [the V1->V2 cost testing](https://github.com/citycoins/contracts/issues/201) outlined before.

## Initial Cost Testing

Following the work done in #19 we're at a point where we can get a baseline comparison between the operations in both contracts.

More data will be added to the repo and a more granular analaysis will be available, saved both in the repo as well as documented in this issue.

Using Tx Per Block as a general measure of cost, the following tables show the differences between the original protocol against the DAO-created functions.

## Unique IDs

| Function                      | min  | max  | avg  |
| ----------------------------- | ---- | ---- | ---- |
| v2: get-or-create-user-id     | 861  | 861  | 861  |
| ccd003: get-or-create-user-id | 1073  | 1073  | 1073  |
| ccd004: get-or-create-city-id | 1080  | 1080  | 1080  |
|                               |      |      |      |
| v2: get-user-id               | 146  | 146  | 146  |
| ccd003: get-user-id           | 2799 | 2799 | 2799 |
| ccd003: get-user              | 3285 | 3285 | 3285 |
|                               |      |      |      |
| ccd004: get-city-id           | 3369 | 3369 | 3369 |
| ccd004: get-city-name         | 3344 | 3344 | 3344 |

**Notes**

- `get-or-create-user-id` is private in v2, but we can use the min value from `register-user` in the core contract since the main operation is to register the user and increase the nonce
- the read-only operations here are MUCH cheaper because they are not loading the entire core contract

## Activation

| Function                             | min | max | avg |
| ------------------------------------ | --- | --- | --- |
| v2: register-user                    | 861 | 146 | 189 |
| ccd005: activate-city                | 289 | 273 | 281 |
|                                      |     |     |     |
| ccd005: is-city-activated            | 568 | 568 | 568 |
| ccd005: get-city-activation-details  | 559 | 559 | 559 |
| ccd005: get-city-coinbase-info | 523 | 523 | 523 |
| ccd005: get-city-treasury-id         | 561 | 561 | 561 |

**Notes**

The majority of functions in here are getters and setters for city-keyed maps that track city details used in other contracts.

## Mining

| Function                          | min | max | avg |
| --------------------------------- | --- | --- | --- |
| v2: mine-tokens                   | 142 | 127 | 131 |
| v2: mine-many                     | 135 | 9   | 100 |
| ccd006: mine                      | 319 | 8   | 139  |
|                                   |     |     |     |
| v2: claim-mining-reward           | 144 | 64  | 93  |
| ccd006: claim-mining-reward       | 402 | 73  | 126  |
|                                   |     |     |     |
| v2: is-block-winner               | 143 | 123 | 132 |
| ccd006: is-block-winner           | 293 | 261 | 277 |
|                                   |     |     |     |
| ccd006: get-coinbase-amount       | 115  | 115  | 115  |
| ccd006: get-mining-stats-at-block | 450 | 450 | 450 |
| ccd006: get-miner-at-block        | 446 | 446 | 446 |

**Notes**

- general operations are cheaper overall
- `mine` and `claim-mining-reward` are more expensive when maxed out

### Stacking

| Function                      | min | max | avg |
| ----------------------------- | --- | --- | --- |
| v2: stack-tokens              | 143 | 46  | 67  |
| ccd007: stack                 | 410 | 31  | 93  |
|                               |     |     |     |
| v2: claim-stacking-reward     | 143 | 103 | 125 |
| ccd007: claim-stacking-reward | 411 | 86  | 207 |
|                               |     |     |     |
| v2: get-stacking-reward       | 161 | 161 | 161 |
| ccd007: get-stacking-reward   | 245 | 240 | 242 |

**Notes**

- general operations are cheaper overall
- `stack` and `claim-stacking-reward` are more expensive when maxed out

**Updated:** added most recent numbers from cost testing iteration 10

### PR DESCRIPTION
**Pull request by whoabuddy**
This PR brings over the current code for the CityCoins protocol and separates into different extensions for the DAO based on the revisions in CCIP-012 and CCIP-013.

- fixes #14
- fixes #15 
- fixes #17 
- fixes #20 
- fixes #23
- fixes #26 
- fixes #27 
- fixes #28 
- fixes #29 
- fixes #31
- fixes #33

### CODE REVIEW

**Comment by whoabuddy** [comment]
Weird - the action is failing with different output from what I see locally.

Using `clarinet-cli 1.0.6` on my device, result of `clarinet check` is 45 warnings, 32 contracts checked.

Using the GH action, result of `clarinet check` is 44 warnings, 6 errors, all referencing:

`error: use of unresolved contract 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccd002-treasury-mia'`

The `mia` and `nyc` versions are derived from the same source here in Clarinet.toml:

https://github.com/citycoins/protocol/blob/2f7f3a6dd0d8574af85dea5019f47febc9258284/Clarinet.toml#L28-L32

Going to see if I can replicate locally with the latest release `1.1.0`.

**Comment by lgalabru** [comment]
hey @whoabuddy! as a quick workaround, instead of using latest here:
https://github.com/citycoins/protocol/blob/40a23d846a00bafe676749d3c98beb3d44c24561/.github/workflows/test-contracts.yaml#L28
you could use 1.0.6, if that version was working for you.
I will be investigating this regression, my apologies for the inconvenience.

**Comment by whoabuddy** [comment]
@radicleart we should be at a good point to continue writing the tests for CCD004 and CCD005 - I made some updates and commented out some functions that weren't working in the former. CCD006 will quickly follow, and I'll have more bandwidth to work on the tests or answer any questions if needed!

**Comment by radicleart** [comment]
Ok @whoabuddy will press on.

**Comment by whoabuddy** [comment]
Changing this from draft -> ready for review. Given it's size it would be great to set this as a baseline and assess what tasks are left. We're getting very close!

Shout out to @radicleart for getting the test coverage up over 90% so far!

We have the majority of the protocol setup, and the immediate next steps would be:

- review some baseline cost testing against the old contracts
- identify any outstanding tasks in the Clarity code
- compare and identify any missing test patterns, e.g.
  - check all error paths, then success paths
  - check min/mid/max of variable length inputs

**Comment by radicleart** [comment]
Also 

- [ ] review coverage post costs refactor and add missing tests

**Comment by whoabuddy** [comment]
@radicleart yes coverage should remain the same, some tests had to be modified along the way but nothing was removed/added iirc. 

Follow-up items to this PR are listed out in #34 and feel free to add anything if missing! Going to merge this now so we can start fresh.

**Pull request merged**
