### PR TITLE
Feat/test treasury

### PR DESCRIPTION
**Pull request by radicleart**
Notes on this PR.

1. I added simple sip-010 external governance token contracts ccext-governance-token-nyc/mia instead of pulling the token contracts from the contracts repo. We can iterate here by either pulling in the original token contracts or adding correct features as needed - e.g. I stuck with the executor dao minting of the gov. token in this first iteration to keep things simple but imagine this will need to evolve.
2. I used the `clarinet requirement` feature to added dependencies to mainnet contracts for sip-009/010 traits. This works for devnet and mainnet deployment but trait refs will need to be corrected for testnet deployment.
3. The test proposals reference the tests through their `description` field - so you can jump to a specific test from the proposal.
4. I tried to keep the test proposals simple which pushes more complexity into the test. Test proposal 008 works the other way - the proposal handles the arrange and act parts of the test, keeping the test simple.

### CODE REVIEW

**Comment by whoabuddy** [comment]
> I added simple sip-010 external governance token contracts ccext-governance-token-nyc/mia instead of pulling the token contracts from the contracts repo. We can iterate here by either pulling in the original token contracts or adding correct features as needed - e.g. I stuck with the executor dao minting of the gov. token in this first iteration to keep things simple but imagine this will need to evolve.

This confused me at first, but I'd rather leave them now and see how we can use them alongside the mainnet contracts. Given the transition will happen without changing the token contracts, we'll have to interact with the current MIA/NYC mainnet contract code. It's also a good template for how a current xDAO gov token works.

> I used the clarinet requirement feature to added dependencies to mainnet contracts for sip-009/010 traits. This works for devnet and mainnet deployment but trait refs will need to be corrected for testnet deployment.

Is that expected behavior? It might be worth filing an issue!

> The test proposals reference the tests through their description field - so you can jump to a specific test from the proposal.

That's helpful, thank you! I like this. Side note - it looks like we might have two different configs for prettier running, so we probably want to define a standard for the project. I opened an issue for it (#20).

> I tried to keep the test proposals simple which pushes more complexity into the test. Test proposal 008 works the other way - the proposal handles the arrange and act parts of the test, keeping the test simple.

This looks like we will have to find an interesting balance, with the 10 test proposals all in that folder it's hard to read, maybe we make a subfolder `test-proposals` so at least the two types are differentiated? I didn't realize how many proposals we'd need but it makes sense given each one has steps that have to be first taken by the DAO.

**Comment by whoabuddy** [comment]
I did a test merge locally and it looks like the only conflict between this and my open PR for migration is the Clarinet.toml.

Should we merge the two now then start fresh so you can start working on texts for the next set of extensions?

**Comment by radicleart** [comment]
Great - thanks for this. I just started along the same lines. I've branched from PR-19 and merged in PR-18. Assuming nothing else changes it should be safe to create a new PR from this merged branch which has the fully tested contracts.

Will take note of your comments also - thanks. We definitely need to keep things tidy because of the number of test proposals needed to nudge the DAO into the right state for the tests.

```Given the transition will happen without changing the token contracts, we'll have to interact with the current MIA/NYC mainnet contract code.```

As in copy them into the `contracts/external` folder ?

**Comment by whoabuddy** [comment]
> Given the transition will happen without changing the token contracts, we'll have to interact with the current MIA/NYC mainnet contract code.
> 
> As in copy them into the contracts/external folder ?

No I think we can use Clarinet requirements for this, it'd be a nice way to see if the feature works as intended (at least in my head). What was the issue you ran into with testnet addresses though? You have to manually update something?

**Comment by whoabuddy** [comment]
Closing this as we've merged the existing tests into the main protocol upgrade PR #19

**Pull request closed without merging**
